name: Deploy Firebase Config

on:
  push:
    branches:
      - main

jobs:
  firestore:
    name: Deploy firestore
    environment: Production
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4
      - name: Deploy to Firestore
        uses: w9jds/firebase-action@v12.9.0
        with:
          args: deploy --only firestore
        env:
          GCP_SA_KEY: ${{ secrets.GCP_SA_KEY }}
          PROJECT_ID: rental-buddy-dev
          PROJECT_PATH: rental-buddy
