name: Run scraper
on:
  schedule:
    - cron: '0 14 * * *'
jobs:
  scrape:
    runs-on: ubuntu-latest
    environment: scrape-env
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '14'
    - run: npm ci
    - run: npm run scrape 
      env:
        PASSWORD: ${{ secrets.PASSWORD }}
        EMAIL: ${{ secrets.EMAIL }}
        NODE_ENV: production
