name: Run navy yard scraper
on:
  workflow_dispatch:
  schedule:
    - cron: '0 12 * * 5'
jobs:
  scrape-navy-yard:
    runs-on: ubuntu-latest
    environment: scrape-env
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '14'
    - run: cd navy-yard && npm ci && npm run navy-yard
      env:
        NAVY_YARD_PASSWORD: ${{ secrets.NAVY_YARD_PASSWORD }}
        NAVY_YARD_EMAIL: ${{ secrets.NAVY_YARD_EMAIL }}
        NODE_ENV: production
  scrape-wework:
    runs-on: ubuntu-latest
    environment: scrape-env
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '14'
    - run: cd navy-yard && npm ci && npm run wework
      env:
        WEWORK_PASSWORD: ${{ secrets.WEWORK_PASSWORD }}
        WEWORK_EMAIL: ${{ secrets.WEWORK_EMAIL }}
        NODE_ENV: production
